# Copyright (C) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: verrazzano-cluster-operator
  labels:
    app: verrazzano-cluster-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verrazzano-cluster-operator
  template:
    metadata:
      labels:
        app: verrazzano-cluster-operator
    spec:
      containers:
      - name: verrazzano-cluster-operator
        image: REPLACE_IMAGE
        imagePullPolicy: Never
        args:
          - --v=4
          # These are dummy values as Rancher is currently not installed
          - --rancherURL=https://my-rancher.com:443
          - --rancherUserName=test
          - --rancherPassword=test
          - --rancherHost=test
      serviceAccount: verrazzano-cluster-operator
