# Copyright (C) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: verrazzano-cluster-operator
  labels:
    app: verrazzano-cluster-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verrazzano-cluster-operator
  template:
    metadata:
      labels:
        app: verrazzano-cluster-operator
    spec:
      containers:
      - name: verrazzano-cluster-operator
        image: <DOCKER-REPO-TAG>/<DOCKER-NAMESPACE-TAG>/verrazzano/verrazzano-cluster-operator:<IMAGE-TAG>
        imagePullPolicy: Always
        args:
          - --v=4
          - --rancherURL=https://my-rancher.com:443
      serviceAccount: verrazzano-cluster-operator
